events {}

http {
    server {
        listen 10000;

        root /var/www/html;
        index index.php;

        # Normal files serve karo
        location / {
            try_files $uri $uri/ =404;
        }

        # PHP files PHP-FPM se process karo
        location ~ \.php$ {
            fastcgi_pass 127.0.0.1:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            include fastcgi_params;
        }
    }
}
